import os
import time
import urllib.request
from flask import Flask, render_template, request, send_file, jsonify
from werkzeug.utils import secure_filename

# --- 1. IMPORTS & SETUP ---
from google import genai
from google.genai.types import (
    Image,
    ProductImage,
    RecontextImageConfig,
    RecontextImageSource,
)

# Configure project
PROJECT_ID = os.environ.get("GOOGLE_CLOUD_PROJECT", "your-project-id-here") 
LOCATION = os.environ.get("GOOGLE_CLOUD_REGION", "us-central1")

# Initialize Client
# Note: Ensure your environment has credentials set up (e.g. gcloud auth application-default login)
try:
    client = genai.Client(vertexai=True, project=PROJECT_ID, location=LOCATION)
except Exception as e:
    print(f"Warning: Could not initialize GenAI client. Check credentials. Error: {e}")
    client = None

virtual_try_on = "virtual-try-on-preview-08-04"

app = Flask(__name__)
UPLOAD_FOLDER = 'uploads'
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

# --- 2. HELPER FUNCTIONS ---
def download_image_from_url(url, save_path):
    try:
        opener = urllib.request.build_opener() 
        opener.addheaders = [('User-Agent', 'Mozilla/5.0')]
        urllib.request.install_opener(opener)
        urllib.request.urlretrieve(url, save_path)
        return save_path
    except Exception as e:
        print(f"Failed to download {url}: {e}")
        return None

def run_ai_virtual_try_on(person_image_path, clothing_image_path):
    if not client:
        raise Exception("GenAI Client not initialized")

    print(f"Running AI on {person_image_path} and {clothing_image_path}")
    
    # The model is designed to preserve the face in the person_image
    # We ensure safety filters are set but allow reasonable generation
    response = client.models.recontext_image(
        model=virtual_try_on,
        source=RecontextImageSource(
            person_image=Image.from_file(location=person_image_path),
            product_images=[
                ProductImage(product_image=Image.from_file(location=clothing_image_path))
            ],
        ),
        config=RecontextImageConfig(
            output_mime_type="image/jpeg",
            number_of_images=1,
            safety_filter_level="BLOCK_LOW_AND_ABOVE", 
        ),
    )
    
    # Generate a unique filename
    timestamp = int(time.time())
    result_filename = f"result_{timestamp}_{os.path.basename(person_image_path)}.jpeg"
    result_path = os.path.join(app.config['UPLOAD_FOLDER'], result_filename)
    
    if response.generated_images:
        response.generated_images[0].image.save(result_path)
        print(f"Result image saved to: {result_path}")
        return result_path
    else:
        raise Exception("No image generated by AI service")

# --- 3. ROUTES ---
@app.route('/')
def index():
    return render_template('index.html')

@app.route('/combine', methods=['POST'])
def combine():
    # --- 1. Input Validation ---
    if 'person_upload' not in request.files:
        return jsonify({'error': 'No person image uploaded'}), 400

    person_file = request.files['person_upload']
    product_url = request.form.get('product_url')
    product_file = request.files.get('product_upload')

    if not product_url and not product_file:
        return jsonify({'error': 'No product image provided'}), 400
        
    if person_file.filename == '':
        return jsonify({'error': 'No selected person file'}), 400

    # --- 2. File Handling ---
    files_to_cleanup = []
    
    try:
        # Save Person Image
        person_filename = f"person_{int(time.time())}_{secure_filename(person_file.filename)}"
        person_path = os.path.join(app.config['UPLOAD_FOLDER'], person_filename)
        person_file.save(person_path)
        files_to_cleanup.append(person_path)
        
        # Save Product Image
        clothing_path = None
        if product_file:
            prod_filename = f"prod_{int(time.time())}_{secure_filename(product_file.filename)}"
            clothing_path = os.path.join(app.config['UPLOAD_FOLDER'], prod_filename)
            product_file.save(clothing_path)
            files_to_cleanup.append(clothing_path)
        elif product_url:
            prod_filename = f"prod_url_{int(time.time())}.jpg"
            clothing_path = os.path.join(app.config['UPLOAD_FOLDER'], prod_filename)
            if not download_image_from_url(product_url, clothing_path):
                return jsonify({'error': 'Failed to download product URL'}), 400
            files_to_cleanup.append(clothing_path)

        # --- 3. AI Generation ---
        result_path = run_ai_virtual_try_on(person_path, clothing_path)
        files_to_cleanup.append(result_path)
            
        return send_file(result_path, mimetype='image/jpeg')
            
    except Exception as e:
        print(f"Error processing request: {e}")
        return jsonify({'error': str(e)}), 500
        
    finally:
        # Cleanup temp files to save space
        for path in files_to_cleanup:
            try:
                if os.path.exists(path):
                    os.remove(path)
            except Exception as e:
                print(f"Error cleaning up {path}: {e}")

if __name__ == '__main__':
    port = int(os.environ.get("PORT", 8080))
    app.run(debug=True, host='0.0.0.0', port=port)
